version: '3.4'

services:
  admin:
    image: ./Admin/Dockerfile
    environment:
      - ASPNETENVIRONMENT=Production
      - PsglOptions__ConnectionString=Host=localhost; Database=mygallery; Port=5432; User Id=postgres; Password=default;
      - HelpOptions__HelpLink=helplink
    ports:
      - "5000:80"
    depends_on:
      - postgres
  ui:
    image: ./UI/Dockerfile
    environment:
      - ASPNETENVIRONMENT=Production
      - PsglOptions__ConnectionString=Host=localhost; Database=mygallery; Port=5432; User Id=postgres; Password=default;
      - HelpOptions__HelpLink=helplink
    ports:
      - "7000:80"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=default
    ports:
      - "5434:5434"